### ISSUE TITLE
Sonar

### ISSUE THREAD

**Issue by QuinnBast** [Subterfuge-Revived/Remake-Core#11]
Sonar ranges and visibility is currently not implemented. Taking on this task would include providing a base sonar range, determining if objects are visible to specific players/outposts and modifying the sonar range for a sub/outpost if a specialist with sonar modification effect is at that location.

There should ideally be an interface `ISonar` which enforces methods such as `getSonarRange()` and `setSonarRange()` as well as `isVisible(ITargetable)` to determine if something is visible. Then this interface can be applied to outposts and subs.

Note: specialists not yet implemented so ignore them for now, just having an interface which allows setting or modifying the sonar range

**Comment by Jaronex** [comment]
I'll work on this!

**Comment by QuinnBast** [comment]
I have implemented this into core
