### ISSUE TITLE
Shields

### ISSUE THREAD

**Issue by QuinnBast** [Subterfuge-Revived/Remake-Core#12]
Core currently doesn't deal with shields. This issue would involve creating an interface for any shield-bearing entity that enforces methods such as `getShields()`, `setShields()`, `getMaximumShields()`, `setMaximumShields()`, `getShieldRecahrdRate()`, `setShieldRechargeRate()`.

Classes implementing a shield interface should not just store the `int shields` as a value for the current number of shields. Instead they should have a `lastCombat` variable and a `lastShield` variable. This allows interpolating the shield value at a specific tick & allows using the shieldRegenrationRate to easily determine the current shield value. This is easier than needing to manually increase the # of shields every time a `ShieldGenerationEvent` occurs which would have to be generated and stored in the time machine for processing.

Potentially have a `ShieldManager` which deals with all things shields for an object.

**Comment by CrasherAsh** [comment]
I want to try to help with this.

**Comment by naib864** [comment]
What is still to be done in this issue?
