### ISSUE TITLE
Unowned Outpost Fix

### ISSUE THREAD

**Issue by QuinnBast** [Subterfuge-Revived/Remake-Core#126]
## Enhancement Description
Unowned outposts should start with 0 drillers and also not be able to regenerate any shields. This makes it easier for players to claim a stake and grab some land. This is how the original subterfuge game does it, and it doesn't make sense for neutral outposts to be heavily guarded.

This should be a quick fix

**Comment by apophis981** [comment]
As per discord conversation:
'The problem in this task is probably in the Outpost constructor and the drillerProducer code — I think they will produce for anyone and we should filter to not produce on “null” owners'

**Comment by apophis981** [comment]
Pull request created:
https://github.com/Subterfuge-Revived/Remake-Core/pull/129
