### ISSUE TITLE
Outpost Names

### ISSUE THREAD

**Issue by QuinnBast** [Subterfuge-Revived/Remake-Core#13]
In unison with the Unity team.

Outposts will need to have a list of generated names. Note: The name that is generated for an outpost MUST be the same when the game is reloaded. This means that selecting the outpost names must be done through the `SeededRandom` classes using the game's seed to ensure that it will always select the same name for the outpost.

Outpost names should:
- Not be specific to a language
- Be universally understood

Names like "Green Forest" are not valid as this is different in many languages. But things like "London" or "New York" are possibilities as they are proper nouns and won't change based on your language. Someone who speaks french and someone who speaks English should both understand that "London" is the same spot.

The generated class should be dynamic and allow names to be easily added to the list.

**Comment by Eliclax** [comment]
I think we shouldn't worry about the actual outpost names for now. If we need a list of names, it's probably in everyone's best interest to just use the list that Subterfuge already has. We can then change them later on in development.
