### ISSUE TITLE
Optimize Pirate Targeting

### ISSUE THREAD

**Issue by QuinnBast** [Subterfuge-Revived/Remake-Core#3]
The current priate targeting algorithm is a linear search until the two points on the course collide. This is inefficient and the point can be found immediately with a bit of calculus or quadratic equation. I was able to determine how to do this when creating the code.

If you can update the `SUB.getTargetLocation(Vector2, int)` function to be O(1) instead of O(n) that would greatly optimize performance of determining the destination of a pirate.

**Comment by naib864** [comment]
I'll take care of that.

**Comment by QuinnBast** [comment]
May potentially be useful:

https://stackoverflow.com/questions/29919156/calculating-intercepting-vector
