### ISSUE TITLE
Hire currency

### ISSUE THREAD

**Issue by QuinnBast** [Subterfuge-Revived/Remake-Core#31]
## Enhancement Description

In order for players to be able to hire specialists, players must be given a type of currency that can be used in order to hire specialists. This task is not about implementing the specialists system or the system to offer potential hires to the player, but this system simply provides a currency system for the player to be able to use once a hire system is implemented.

## Solution

This feature should have:
- Players are provides a currency
- The player’s currency can be increased or decreased.
- A “PlayerCurrencyEvent” is created which provides players an increase in their currency on regular intervals
- a player cannot go into debt when spending currency.

It was suggested that there are multiple currencies (like tokens) so the system should be designed in a way that adding additional currencies is easily done, potentially through a `Bank` and a `Transaction` when purchasing

**Comment by Nerarith** [comment]
I want to work on this.
