### ISSUE TITLE
[Server] Add Player Management Endpoints

### ISSUE THREAD

**Issue by QuinnBast** [Subterfuge-Revived/Remake-Core#76]
## Enhancement Description
Admins should be able to ban players from the game. There should be various levels of bans. Implement some endpoints to allow admins to ban players from accessing the game.

Once bans are implemented, make sure that if a player is banned, all requests to endpoints other than the login endpoint are blocked with a "BANNED" response. (This can be done in the gRPC interceptor)

Implement the following endpoint:

```
rpc GetAllPlayers(GetAllPlayersRequest) returns GetAllPlayersResponse {}
rpc BanPlayer(BanPlayerRequest) returns BanPlayerResponse {}
```

Banning a player should have:
- TempBan - for a specified number of hours
- PermaBan - forever
If a player is temp banned, when the player attempts to login we should check their roles and if they are temp banned, check the timeout for the ban. We will likely need to add a database for Bans or add a field to the Player table such as `BannedUntil`, which would get set if their role is one of the banned roles.

The `GetAllPlayers` endpoint should return a list of all players as well as more confidential information for admins, for example, the device identifier and the email registered. Do NOT return the player's passwords (even though they are hashed). 

Additionally, it may be useful to have an endpoint for:
```
rpc GetPlayerChatLogs(GetPlayerChatLogsRequest) returns GetPlayerChatLogsResponse {}
```

This would allow us to view all of a player's chat messages (grouped by GameID maybe?) so that we can verify if a player has been sending malicious chat messages.

**Comment by Pheric** [comment]
Device identifiers should be stored salted and hashed so they can only identify players within the Subterfuge ecosystem and not be so easy to correlate with advertisers, etc.
